//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Guest!.
        /// </summary>
        internal static string SiteGuestWelcome {
            get {
                return ResourceManager.GetString("SiteGuestWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        internal static string SiteMemberWelcome {
            get {
                return ResourceManager.GetString("SiteMemberWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetShoutout is a place where you can find latest Microsoft .NET stories to increase your skills and share your opinions..
        /// </summary>
        internal static string SiteMetaDescription {
            get {
                return ResourceManager.GetString("SiteMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnetshoutout, .net, dotnet, asp.net, asp.net mvc, aspnetmvc, mvc, c#, vb.net, sql, ajax, silverlight, wpf, wcf, wf, linq, windows forms, web service, visual studio, tdd, azure, css, css3, html, html5, javascript, jquery, microsoft, programming, development, dotnet latest news, dotnet latest stoy, .net latest stoy, .net latest news.
        /// </summary>
        internal static string SiteMetaKeywords {
            get {
                return ResourceManager.GetString("SiteMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SiteSignin {
            get {
                return ResourceManager.GetString("SiteSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string SiteSignout {
            get {
                return ResourceManager.GetString("SiteSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SiteSignup {
            get {
                return ResourceManager.GetString("SiteSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiGG.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiGG.
        /// </summary>
        internal static string SiteTitlePrefix {
            get {
                return ResourceManager.GetString("SiteTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit new story.
        /// </summary>
        internal static string StorySubmitNew {
            get {
                return ResourceManager.GetString("StorySubmitNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming stories.
        /// </summary>
        internal static string StoryUpcoming {
            get {
                return ResourceManager.GetString("StoryUpcoming", resourceCulture);
            }
        }
    }
}
